IS_CLICK_HAND_ON = False
IS_POINTER_HAND_ON = False


# max tip points tracked, will effect for stabilizer function
MAX_TIP_POINTS = 5

'''
Click hand
'''
CLICK_HAND_TIP_POINT_COLORS = (255, 0, 0)
CLICK_HAND_BOX_COLOR = (0, 0, 255)

CLICK_HAND_LEFT_CLICK_LEFT_BOX_PERCENTAGE = 0.15
CLICK_HAND_LEFT_CLICK_BOTTOM_BOX_PERCENTAGE = 0.2
CLICK_HAND_LEFT_CLICK_BOX_SIZE_TO_SCREEN = 0.15

CLICK_HAND_RIGHT_CLICK_LEFT_BOX_PERCENTAGE = 0.15
CLICK_HAND_RIGHT_CLICK_BOTTOM_BOX_PERCENTAGE = 0.45
CLICK_HAND_RIGHT_CLICK_BOX_SIZE_TO_SCREEN = 0.15

MAX_CLICK_DISTANCE = 0.17

'''
Pointer hand
'''
POINTER_HAND_TIP_POINT_COLORS = (0, 255, 0)
POINTER_HAND_BOX_COLOR = (230, 230, 250)

POINTER_HAND_LEFT_BOX_PERCENTAGE = 0.4
POINTER_HAND_BOTTOM_BOX_PERCENTAGE = 0.3
POINTER_HAND_BOX_SIZE_TO_SCREEN = 0.45